version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - cd /home/ubuntu/server
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
artifacts:
  files:
    - '**/*'
  name: helloreact
